// src/types/AppState.ts
export enum AppPageType {
    LOGIN = 'LOGIN',
    REGISTRATION = 'REGISTRATION',
    EMPLOYEE_LIST = 'EMPLOYEE_LIST',
    CALENDAR = 'CALENDAR',
    SUPERVISORCALENDAR = 'SUPERVISORCALENDAR',
    ADMINCONSOLE = 'ADMINCONSOLE',
    SETTINGS = 'SETTINGS',
    APPROVAL = 'APPROVAL',
  }
  